# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2496cb8f032320d5f3ceee155501624f2ab444f95383cc1e204ec28fe2a47406c604a70dee514d45d6592861741132e96e27c51fada7d6303a60c2d766e3e15

test:
  secret_key_base: c6075fa782840d72366dd2a8024a98983cd11da5cf2b283251e69be70692c9aed7dffbd17a35f0f0e0c1666f688000a08e59c0b2f272daee7d86310fd05e0773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
